// <auto-generated />
using System;
using FileService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace FileService.Migrations
{
    [DbContext(typeof(FileDbContext))]
    partial class FileDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0")
                        .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("FileService.Models.CodeFile", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").UseIdentityColumn();
                b.Property<string>("Content").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<int>("CreatedByUserId").HasColumnType("int");
                b.Property<bool>("IsFolder").IsRequired().HasColumnType("bit");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<int?>("ParentFolderId").HasColumnType("int");
                b.Property<int>("ProjectId").HasColumnType("int");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("ParentFolderId");
                b.HasIndex("ProjectId");
                b.ToTable("CodeFiles");
            });

            modelBuilder.Entity("FileService.Models.CodeFile", b =>
            {
                b.HasOne("FileService.Models.CodeFile", null)
                    .WithMany("Children")
                    .HasForeignKey("ParentFolderId")
                    .OnDelete(DeleteBehavior.Restrict);
            });
#pragma warning restore 612, 618
        }
    }
}
