// <auto-generated />
using System;
using ExecutionService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExecutionService.Migrations
{
    [DbContext(typeof(ExecutionDbContext))]
    partial class ExecutionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0")
                        .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("ExecutionService.Models.ExecutionJob", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int").UseIdentityColumn();
                b.Property<string>("Code").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("ErrorOutput").HasColumnType("nvarchar(max)");
                b.Property<DateTime?>("ExecutedAt").HasColumnType("datetime2");
                b.Property<string>("Language").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Output").HasColumnType("nvarchar(max)");
                b.Property<int>("ProjectId").HasColumnType("int");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<int>("UserId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("CreatedAt");
                b.HasIndex("ProjectId");
                b.HasIndex("Status");
                b.HasIndex("UserId");
                b.ToTable("ExecutionJobs");
            });
#pragma warning restore 612, 618
        }
    }
}
