// <auto-generated />
using System;
using NotificationService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace NotificationService.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    partial class NotificationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0")
                        .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("NotificationService.Models.Notification", b =>
            {
                b.Property<int>("NotificationId").ValueGeneratedOnAdd().HasColumnType("int").UseIdentityColumn();
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<bool>("IsRead").HasColumnType("bit");
                b.Property<string>("Message").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<string>("Type").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<int>("UserId").HasColumnType("int");
                b.HasKey("NotificationId");
                b.HasIndex("UserId");
                b.ToTable("Notifications");
            });
#pragma warning restore 612, 618
        }
    }
}
